name = "jonquil"
version = "0.2.0"
license = "Apache-2.0 OR MIT"
maintainer = ["@awvwgk"]
author = ["Sebastian Ehlert"]
copyright = "2022 Sebastian Ehlert"
homepage = "https://toml-f.readthedocs.io/en/latest/how-to/jonquil/"
keywords = ["json", "io", "serde"]
description = "Bringing TOML blooms to JSON land"

[dependencies]
toml-f.git = "https://github.com/jinangshah21/toml-f.git"
toml-f.rev = "b54dd6a268a0da88e34e3cfa0e240774f16c760f"

[[test]]
name = "jqtest"
source-dir = "test/unit"
[test.dependencies]
test-drive.git = "https://github.com/fortran-lang/test-drive.git"
